export enum MoviesActionTypes {
  ADD_NOW_PLAYING_MOVIE = 'ADD_NOW_PLAYING_MOVIE',
  LOAD_NOW_PLAYING_MOVIE = 'LOAD_NOW_PLAYING_MOVIE',
  ERROR_NOW_PLAYING_MOVIE = 'ERROR_NOW_PLAYING_MOVIE',
  CHANGE_NOW_PLAYING_CATEGORY = 'CHANGE_NOW_PLAYING_CATEGORY',

  ADD_POPULAR_MOVIE = 'ADD_POPULAR_MOVIE',
  LOAD_POPULAR_MOVIE = 'LOAD_POPULAR_MOVIE',
  ERROR_POPULAR_MOVIE = 'ERROR_POPULAR_MOVIE',
  CHANGE_POPULAR_CATEGORY = 'CHANGE_POPULAR_CATEGORY',

  ADD_UPCOMING_MOVIE = 'ADD_UPCOMING_MOVIE',
  LOAD_UPCOMING_MOVIE = 'LOAD_UPCOMING_MOVIE',
  ERROR_UPCOMING_MOVIE = 'ERROR_UPCOMING_MOVIE',
}
