export { Main } from './Main/Main'
export { NotFound } from './NotFound/NotFound'
export { Premiere } from './Premiere/Premiere'
export { FilmPage } from './FilmPage/FilmPage'
export { News } from './News/News'
export { OneNews } from './OneNews/OneNews'
export { Collections } from './Collections/Collections'
export { SearchResult } from './SearchResult/SearchResult'
export { Profile } from './Profile/Profile'
export { ProfileMain } from './Profile/subpages/ProfileMain/ProfileMain'
export { Setting as ProfileSetting } from './Profile/subpages/Setting/Setting'
export { UserReviews } from './Profile/subpages/UserReviews/UserReviews'
